language: objective-c
osx_image: xcode8
xcode_project: SwiftyXML.xcodeproj
xcode_sdk: iphonesimulator10.0
env:
  global:
  - FRAMEWORK_NAME=SwiftyXML
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage bootstrap
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: b1vgXYNG/JDcbN4xyle8BwXNNCt1VahaQ3MedIpHCf7bHPJi4DJ6eWi8Iie6sK8WxEoDGApBDQMUPtl01QI7tXZo0YYFHMmi7lwMrkxv/k4qqM//ERIeK2Z9/qAxPEkQO1BlIldIoASnKDLuNdLMq/0TDqii3EhV2tppvRSprCoHRM1nsN5/LXNk9Rm4AIfwzto+fwdLC42I9cERXrOpPzFqjuv/JrwCV0ka1OAYqaMj163s6YmL2nS0uc8ZaTxYQx962q+ZiQlZDwUJQ+zpTz0wVJQ9RkZf3pl7Ef2r90XwBLViWJLOPoq4ARTTLlF6Qsrc5dwm42IWyWPiXLMZjHMGmeYOjWPQgqFad9E7aqCBQTZrZ7l+5/bt1dUgjd8L/BATfujvZ7+vkSnBR+HkLT3OV2a/bk9KL+eMwczEBZObMls4UsXMxJEWjHnQ2eD8dQRWzn2buPnIkijU74OiuI4LoR8pKt4nJnSK3wGnk0vhiH3qm/1MjRQWQXhBKWzNmRVAqvTyLRTg4M34zEwk9OwqWsFoHGAvlABDyYWWHvtAx8qsGHJ1by5LCQ+moEJ6ZHpHg9nHQoq0QoxoGDcqUdSQYztahJ4QyTZZ3y0vgu85W6IM4ObFvhjrJhIx5EirAMb0LZLiZtjWoJ1JX4h2DB4bCB6MQ20IiLyiJsyy/lU=
  file: SwiftyXML.framework.zip
  skip_cleanup: true
  on:
    repo: chenyunguiMilook/SwiftyXML
    tags: true
